#!/usr/bin/env bash
# Create a script to insta;; and configure HAProxy on lb-01 server
# Cofigure HAProxy to send traffic to web-01 and web-02 server
# Distribute request using a roundrobin algorithm 
# Make sure that HAProxy can be manage via an init script
# Install and configuer HAProxy on my lb-01 server
sudo apt get -y update
sudo apt-get -y install haproxy

server_config=\
"
frontend ezana-frontend
	bind *:80
	mode http
	defualt_backend ezana-backend
backend ezana-backend
	balance roundrobim
	server 119364-web-01 100.25.165.88:80 check
	server 119364-web-02 34.227.90.127:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/defualt/haproxy

sudo service haproxy restart
